---
title: "Test"
author: "Timothy A Calderwwood; Timothy R. Anderson, PhD, CAP"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
bibliography: references.bib
csl: ../design/ieee-with-url.csl 
---
Validating the Malmquist Productivity Index for Industry Change:  The Case of Major League Baseball
 
# Abstract

Several articles use the Malmquist Productivity Index (MPI) to evaluate different industries performances over time. At issue is these articles use a very small set of DMUs over a short time frame to validate the usefulness of the MPI, as raised by their authors. Therefore, validating MPI properly requires a large and verified data set. To address the number DMU issues and validate the MPI, this article utilizes the Lehman’s Baseball Database, which spans baseballs rich history from 1871 to 2015. First validation happens by picking major events and verifying an index change at that particular time. The second validation takes index change and matches it to an event in baseball history. 

# Introduction 

The Malmquist index was introducing in a paper written by Professor Sten Malmquist in 1953 [@fare_memoriam_2005]. The paper entitled _Index numbers and indifference surfaces_ spelled out the theory of "cost of living indexes and uses the duality between the expenditure and distance functions to integrate price and quantity index indexes in the Consumer context." In 1982, two papers were published that used the Malmquist Index to create what is now affectionately known as the Malmquist Productivity Index (MPI) [@fare_memoriam_2005].  The authors Caves, Christensen and Diewer took the Malmquist Index and developed a producer context to construct an index of productivity change. The first article using Data envelopment analysis (DEA) and Malmquist was written by James Odeck in 1993 [odeck_measuring_1993]. 

## Data envelopment analysis

Introduction to DEA
Data Envelopment Analysis (DEA) used to evaluate several different producers efficiency.  Classic non-DEA methods evaluate producers compare against an average producer. DEA takes another approach and compares producer’s bases on only the best producers of the group. Comparing producers or decision making unit (DMU) fits into what is called extreme point methods. 


This section is an introduction to Data Envelopment Analysis (DEA) for people unfamiliar with the technique. For a more in-depth discussion of DEA, the interested reader is referred to Seiford and Thrall [1990] or the seminal work by Charnes, Cooper, and Rhodes [1978]. 
DEA is commonly used to evaluate the efficiency of a number of producers. A typical statistical approach is characterized as a central tendency approach and it evaluates producers relative to an average producer. In contrast, DEA is an extreme point method and compares each producer with only the "best" producers. By the way, in the DEA literature, a producer is usually referred to as a decision making unit or DMU. Extreme point methods are not always the right tool for a problem but are appropriate in certain cases. (See Strengths and Limitations of DEA.) 
A fundamental assumption behind an extreme point method is that if a given producer, A, is capable of producing Y(A) units of output with X(A) inputs, then other producers should also be able to do the same if they were to operate efficiently. Similarly, if producer B is capable of producing Y(B) units of output with X(B) inputs, then other producers should also be capable of the same production schedule. Producers A, B, and others can then be combined to form a composite producer with composite inputs and composite outputs. Since this composite producer does not necessarily exist, it is sometimes called a virtual producer. 
The heart of the analysis lies in finding the "best" virtual producer for each real producer. If the virtual producer is better than the original producer by either making more output with the same input or making the same output with less input then the original producer is inefficient. Some of the subtleties of DEA are introduced in the various ways that producers A and B can be scaled up or down and combined. 
The procedure of finding the best virtual producer can be formulated as a linear program. Analyzing the efficiency of n producers is then a set of n linear programming problems. The following formulation is one of the standard forms for DEA. lambda is a vector describing the percentages of other producers used to construct the virtual producer. lambda X and lambda Y and are the input and output vectors for the analyzed producer. Therefore X and Y describe the virtual inputs and outputs respectively. The value of theta is the producer's efficiency. 
DEA Input-Oriented Primal Formulation 
 
It should be emphasized that an LP of this form must be solved for each of the DMUs. There are other ways to formulate this problem such as the ratio approach or the dual problem but I find this formulation to be the most straightforward. The first constraint forces the virtual DMU to produce at least many outputs as the studied DMU. The second constraint finds out how much less input the virtual DMU would need. Hence, it is called input-oriented. The factor used to scale back the inputs is theta and this value is the efficiency of the DMU. 



# Malquist

Before using the Malmquist Productivity Index, it must be validated in this use. Is it valid for locating changes in technical progress or technical efficiency, thus allowing us to identify the cause?

To validate Malmquist Productivity Index, a large amount of verified data is required. The data must be One data source that meets these requirements is Baseball Player performance data for 1871 through 2014 found in the Lahman Baseball Database.  The advantages of using this database is
·         Long history of sophisticated methods applied to baseball
·         Can provide better understanding to the underlying models
·         Rich and very accurate historical data
·         Well understood history and easily understood application
Using the database to validate the Malmquist Productivity Index, we can prove the following hypotheses
·         H1:  Immature industries show highly variable performance
·         H2: Rule changes, etc. result in a significant frontier shift
o   In favor of hitters will result in a positive frontier shift in the the year that they first take effect
o   In favor of pitchers (against hitters) will result in a negative frontier shift in the the year that they first take effect
·         H3: New and “Exceptional” performers (ex. with new best practices) will result in:
o   A positive industrywide frontier shift in their their “first” year (P>1)
o   Decrease in efficiency as most people suffer in comparison to the star. (E<1)
o   Returns to stable if their performance stays at that level, later years (P, E=1)
·         H4:  Years without changes should generally have little frontier shift
o   Both frontier shift and efficiency change are about 1.0 (P, E=1)
 

